services:
  postgres:
    image: postgres:16.8-alpine3.20
    restart: always
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finance_db
    ports:
      - "5432:5432"